// src/components/layouts/Footer.tsx
"use client";

import {
  Box,
  Container,
  Stack,
  Text,
  useColorModeValue,
  Flex,
  Link,
  Icon,
} from "@chakra-ui/react";
import { FaGithub, FaTwitter, FaLinkedin } from "react-icons/fa";

export default function Footer() {
  const bgColor = useColorModeValue("gray.50", "gray.900");
  const borderColor = useColorModeValue("gray.200", "gray.700");

  return (
    <Box
      bg={bgColor}
      borderTop={1}
      borderStyle={"solid"}
      borderColor={borderColor}
    >
      <Container
        as={Stack}
        maxW={"container.xl"}
        py={4}
        spacing={4}
        justify={"center"}
        align={"center"}
      >
        <Flex gap={6}>
          <Link href={"#"} isExternal>
            About
          </Link>
          <Link href={"#"} isExternal>
            Contact
          </Link>
          <Link href={"#"} isExternal>
            Privacy Policy
          </Link>
        </Flex>
        <Stack direction={"row"} spacing={6}>
          <Link href={"#"} isExternal>
            <Icon as={FaTwitter} w={6} h={6} />
          </Link>
          <Link href={"#"} isExternal>
            <Icon as={FaGithub} w={6} h={6} />
          </Link>
          <Link href={"#"} isExternal>
            <Icon as={FaLinkedin} w={6} h={6} />
          </Link>
        </Stack>
        <Text>© 2024 Soccer Player Tracker. All rights reserved</Text>
      </Container>
    </Box>
  );
}

// _New-Vue-UI/team-tracker-vue/src/components/layouts/Footer.vue
<template>
  <footer class="footer">
    <el-row justify="center" class="footer-links">
      <el-link href="#" target="_blank">About</el-link>
      <el-link href="#" target="_blank">Contact</el-link>
      <el-link href="#" target="_blank">Privacy Policy</el-link>
    </el-row>
    <el-row justify="center" class="footer-social">
      <el-link href="#" target="_blank"><i class="fab fa-twitter"></i></el-link>
      <el-link href="#" target="_blank"><i class="fab fa-github"></i></el-link>
      <el-link href="#" target="_blank"><i class="fab fa-linkedin"></i></el-link>
    </el-row>
    <el-row justify="center">
      <span>© 2024 Soccer Player Tracker. All rights reserved</span>
    </el-row>
  </footer>
</template>

<script setup>
// No script needed for static footer
</script>

<style scoped>
.footer {
  /* margin: 0; */
  /* Remove unnecessary margins */
  /* padding: 16px 0; */
  /* Add padding for spacing */
  text-align: center;
  background: var(--footer-bg);
  color: var(--text-main);
}

.footer-links,
.footer-social {
  margin-bottom: 8px;
  gap: 16px;
}

.footer-social i {
  font-size: 1.5em;
}
</style>
